name = "use-greeting"
version = "0.1.0"
defaultTargets = ["use-greeting"]

[[lean_lib]]
name = "UseGreeting"

[[lean_exe]]
name = "use-greeting"
root = "Main"

[[require]]
name = "trans-greeting-2"
path = "../trans-greeting-2"

[[require]]
name = "trans-greeting-1"
path = "../trans-greeting-1"